name: OriginLanguages
channels:
  - conda-forge
  - r
  - defaults
dependencies:
  - python=3.11
  - pip
  - geos=3.13.0
  - gdal=3.10.1
  - geopandas=1.0.1
  - git
  - pandas=2.2.3
  - pandas-datareader=0.10.0
  - statsmodels=0.14.4
  - xlrd=2.0.1
  - dask=2024.12.1
  - networkx=3.4.2
  - ipykernel=6.29.5
  - ipyparallel=9.0.0
  - ipython=8.31.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.1.5
  - kiwisolver=1.4.7
  - matplotlib=3.10.0
  - scikit-image=0.25.0
  - scikit-learn=1.6.1
  - scipy=1.15.1
  - seaborn=0.13.2
  - geoplot=0.5.1
  - geopy=2.4.1
  - pycountry=24.6.1
  - nb_conda_kernels=2.3.1
  - nbclassic=0.5.1 
  - nbclient=0.7.2 
  - nbconvert=7.2.9 
  - stata_kernel=1.12.2
  - plotly=5.24.1
  - nodejs=22.12.0
  - geocoder=1.38.1
  - html5lib=1.1
  - plotnine=0.14.5
  - ipympl=0.9.6
  - python-kaleido=0.2.1
  - numba=0.60.0
  - jupyter=1.1.1
  - jupyterlab=4.3.4
  - jupyter_contrib_nbextensions=0.7.0
  - jupyter_nbextensions_configurator=0.6.1
  - numpy=2.0.2
  - openpyxl=3.1.5
  - py7zr=0.22.0
  - requests=2.32.3
  - tqdm=4.67.1
  - jinja2=3.1.5
  - r=4.3
  - r-base=4.3.3
  - r-dplyr=1.1.4
  - r-tidyverse=2.0.0
  - r-essentials=4.3
  - r-easypackages=0.1.0
  - r-binsreg=1.1
  - r-data.table=1.15.4
  - r-renv=1.0.11
  - r-ggplot2=3.5.1
  - r-remotes=2.5.0
  - rpy2=3.5.11
  - pip:
      - geonamescache=2.0.0
      - stargazer=0.0.7
      - ipystata=0.3.8
      - pyfixest=0.28.0
      - isounidecode=0.3
      - binsreg=2.1.5
      - rdrobust=1.3.0 
      - lets-plot=4.5.2
      - geostats=0.1
      - hmi=0.1
      - dask-labextension=7.0.0
      - git+https://github.com/cldf-datasets/wals.git@v2020#egg=cldfbench_wals